Chang code according to the new concept names
Bahmni-Covid19/default-config pull request #20
Opened 2021-02-02 09:26 UTC by Mahesh-I

2021-02-02 10:16 UTC, swatigogia2020 commented on .gitignore
> +openmrs/apps/forms/*
remove this file from commit

2021-02-02 10:17 UTC, swatigogia2020 requested changes
remove the .gitignore file from the commit

2021-02-02 10:57 UTC, Mahesh-I commented on .gitignore
> +openmrs/apps/forms/*
removed

2021-02-03 06:03 UTC, praveenadayanand approved these changes

2021-02-03 11:14 UTC, merged